services:
  mysql:
    image: mysql:8.0
    container_name: rhizome-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Seoul

    networks:
      - rhizome-network
    restart: on-failure

  server:
    image: "${DOCKER_USERNAME}/rhizome-server:${BUILD_NUMBER}"
    container_name: rhizome-server
    expose:
      - "8080"
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Seoul
    depends_on:
      - mysql
    networks:
      - rhizome-network
    restart: on-failure

networks:
  rhizome-network:
    driver: bridge
