spring.application.name: rhizome
spring.profiles.active: local

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

# Swagger(OpenAPI) 설정
springdoc:
  version: 1.0.0
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://${database.url}
    username: ${database.username}
    password: ${database.password}

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://${database.url}
    username: ${database.username}
    password: ${database.password}
